### PR TITLE
Feature todo

### PR DESCRIPTION
**Pull request by billodiallo**
In the project I created a simple todo app by following the requirements in Odin page
- Setup webpack to load style files, pictures and bootstrap classes.
-  Create Todo, Project and Organization objects that will be created dynamically. Expand objects with several attributes.
- Add view files and logic for populating projects.
- Add view files and logic for populating projects.
- Add CRUD methods to save to localStorage, update, delete and edit objects in localStorage . I use factory functions to handle them.
- Update readme file.
- Update code to respect  linter rules.

### CODE REVIEW

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @billodiallo    ! :wave: :wave:

#### You have done well so far :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review.

- - -

**Recommended**
- [x] At a minimum the todo items should have a title, description, dueDate and priority. You might also want to include notes or even a checklist. ([Odin Project](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/todo-list))
- Your project is missing the following features:
1. Due date
2. Priority
3. Title
4. Description

- [x] Deploy your app and add the live link to your readme.


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by billodiallo** [comment]
thanks for review , I Added in my project
Due date
Priority
Title
Description

**Review by arslanbisharat — APPROVED** [review]
# Approved :clap:

Hello Developer :wave:

Thank You for submitting this Pull Request. I am thrilled to inform you that your project is approved now. :clap:

You have done a great job. I like your project. 

**To highlight** 

- [ ] You have a descriptive Readme. Nice Job. 
- [ ] Your Pull Request is nice. Good Job!
- [ ] You have deployed your website. Nice!!!
- [ ] You are using linters and no error is present. I am happy to see it. 
- [ ] Your project has met the minimum technical requirements too. 



In short, I am very excited to see this project and proud of you. 

**What to do next?** :thinking:

1- Visit https://dashboard.microverse.org/projects and submit your approved project. 
2- Prepare yourself for the next project. 

I am wishing you very good luck with the next project. :smile:

Once again, Congratulations!:joy:

**Best,
Arslan Bisharat(PT-TSE)
Slack: @arslanbisharat**

**Comment by billodiallo** [comment]
thank you boss

**Pull request merged**
